### ISSUE TITLE
Mou.app like syntax highlighter

### ISSUE THREAD

**Issue by paales** [SchumacherFM/Magento-Markdown#21]
The Mou App has a very nice syntax highlighter:
![schermafbeelding 2013-12-16 om 15 42 18](https://f.cloud.github.com/assets/1244416/1755168/4b1c81e8-6660-11e3-915c-760e63bd412a.png)

I think the main goal a syntax highlighter should achieve is making the text easier to read, being able to work in the editor without losing track of the sections.

Therefor I think it is a good idea to have headers are bigger and (optionally) in a different color, this is also true for special characters.

The main idea is that Markdown is enhanced text and isn't a programming language or something. Text should be written easy, easily readable when editing.

I haven't found any editor/syntax highlighter that is able to do this, but wanted to drop this idea. Also, I believe a syntax highlighter is a nice-to-have and isn't as essential as a good preview functionality.

**Comment by SchumacherFM** [comment]
stale - won't fix.
