### ISSUE TITLE
Error on document.on()

### ISSUE THREAD

**Issue by vernard** [SchumacherFM/Magento-Markdown#37]
On file `markdown\src\js\markdown\adminhtml\markdown.js`

`
document.on('click', 'textarea.initMarkdown', _onClickBuildTabsFactory);
`

Gives this error: `Uncaught TypeError: undefined is not a function`

Upon debugging, I found out that `document` variable does not have the `on()` method. It did work when I changed it to `jQuery(document).on(...)`. 

Our team uses both jquery and prototype and used jQuery.noConflict().

Please help. Thanks.

**Comment by SchumacherFM** [comment]
Please remove jQuery from your Backend.

I'm not gonna fix that.

If you find an appropriate solution for a fix I'm happy to merge your Pull Request.
