### ISSUE TITLE
MediaBrowser (Image Insert...) does not update the content

### ISSUE THREAD

**Issue by azngeek** [SchumacherFM/Magento-Markdown#41]
I wonder, if this has ever worked with this extension as the markdown renders its content in an iframe. If i enable the image insert button and try to insert the image, there whill be no update. I think, that its due to the fact that you are using i frames?

Regards

**Comment by azngeek** [comment]
Okay, it seems that this will not work if you enable the EpicEditor which will use IFrames instead of Tabs

**Comment by SchumacherFM** [comment]
I've jsut tried it without Epic Editor and it worked.

With Epic Editor it is getting also inserted but you need to switch off and then switch on the Epic Editor to reload the content.
